export class PersonalData {
  Id: number;
  Name: string;
  FileNo: string;
  CivilIdNo: string;
  DateBirth: Date;
  DateJoin: Date;
  PhoneNo: string;
  ArticleNo: number;
  PermanencyType: number;
  InsideBuilding: boolean;
  AdvHousing: boolean;
  AdvMobile: boolean;
  AdvVehicle: boolean;
  GenderId: number;
  MasterDepartmentId: number;
  MasterJobDegreeId: number;
  MasterFunctionalGroupId: number;
  MasterDesignationId: number;
  MasterJobTitleId: number;
  MasterJobDescriptionId: number;
  MasterNationalityId: number;
  MasterBudgetTypeId: number;
  MasterJobLevelId: number;
  NextJobLevelId: number;
  NextJobLevelDate: Date;
  MasterGradeId: number;
  CurrentGradeDate: Date;
  NextGradeId: number;
  NextGradeDate: Date;
  CurrentNoOfAllowances: number;
  NextNoOfAllowances: number;
  IsRetired: boolean;
  MasterReasonForRetirementId: number;
  RevisedBy: string;
  DateRevised: Date;
  Notes: string;
  // Id: number;
  // Name: string;
  // FileNo: string;
  // CivilIdNo: string;
  // DateBirth: Date;
  // DateJoin: Date;
  // PhoneNo: string;
  // ArticleNo: number;
  // MasterDepartmentId: number;
  // GenderId: number;
  // PermanencyType: number;
  // InsideBuilding: boolean;
  // MasterFunctionalGroupId: number;
  // MasterDesignationId: number;
  // MasterJobTitleId: number;
  // MasterJobDescriptionId: number;
  // MasterJobLevelId: number;
  // MasterNationalityId: number;
  // AdvHousing: boolean;
  // AdvMobile: boolean;
  // AdvVehicle: boolean;
  // NextJobLevelId: number;
  // NextJobLevelDate: Date;
  // JobGroupId: number;
  // CurrentGradeId: number;
  // NextGradeId: number;
  // BudgetTypeId: number;
  // CurrentNoOfAllowances: number;
  // NextNoOfAllowances: number;
  // CurrentGradeDate: Date;
  // NextGradeDate: Date;
  // ReasonForPromotionId: number;
  // RevisedBy: string;
  // DateRevised: Date;
  // Notes: string;
}
